packages:
  - .
  - plugins/*

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  node-llama-cpp: false

auditConfig: { ignoreGhsas: null }

ignoredBuiltDependencies:
  - protobufjs

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar

patchedDependencies:
  ink@6.8.0: patches/ink@6.8.0.patch
