export {
	buildStatsViewModel,
	computeCumulative,
	computePeakDay,
	computeStreak,
	computeTopPairs,
	filterDailyInRange,
	rangeStartKey,
} from './aggregators';
export {
	addLocalDays,
	monthLabel,
	toLocalDateKey,
	weekdayLabel,
} from './date-utils';
export {
	_cancelPendingFlushForTests,
	_resetStatsRecorderForTests,
	type ApiUsageLike,
	ensureStatsFlushOnShutdown,
	finalizeStatsForExit,
	flushStatsLedgerSync,
	getStatsLedgerCached,
	invalidateStatsCache,
	recordApiCallForStats,
	recordSessionCreated,
	recordTokenUsage,
	recordUserPrompt,
	STATS_SHUTDOWN_HANDLER_NAME,
} from './record';
export {
	applyPromptIncrement,
	applySessionIncrement,
	applyTokenIncrement,
	clearStatsLedger,
	createEmptyLedger,
	getStatsFilePath,
	readStatsLedger,
	STATS_FILE_NAME,
	writeStatsLedger,
} from './storage';
export {
	type CumulativePoint,
	type DailyStats,
	makePairKey,
	PAIR_KEY_SEP,
	type PeakDay,
	parsePairKey,
	STATS_RANGES,
	type StatsLedger,
	type StatsRange,
	type StatsViewModel,
	type StreakInfo,
	type TopPair,
} from './types';
