import type {SecurityScanResult} from './security-scan';
import {formatFindingsSection} from './security-scan';

export interface FormatReviewInput {
	prNumber: number;
	subagentOutput: string;
	scan: SecurityScanResult;
}

/**
 * Composes the subagent's narrative and a deterministic, code-generated
 * semgrep section into a single review body. The semgrep section is never
 * derived from what the LLM said about the findings — it's built directly
 * from `scan`, so its accuracy never depends on model fidelity.
 */
export function formatReviewBody(input: FormatReviewInput): string {
	const {prNumber, subagentOutput, scan} = input;

	return [
		`## Nanocoder Automated Review — PR #${prNumber}`,
		'',
		subagentOutput.trim(),
		'',
		'---',
		'### Static Analysis (semgrep)',
		formatFindingsSection(scan),
		'',
		'---',
		`*Generated by \`nanocoder verify --pr ${prNumber}\` — automated, read-only review (verdict: comment; does not block merge).*`,
	].join('\n');
}
